# Generated by Django 5.0.3 on 2024-03-30 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grokapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='room',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
